name: CI

on: push

jobs:
  ci:
    name: Run tests, lint, and check format.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint --ignore dist
      - run: deno fmt --check
